### ISSUE TITLE
[master] GuermondNeumannBC is not executable

### ISSUE THREAD

**Issue by sebglane** [j507/RotatingMHD#103]
On `master` the application `GuermondNeumannBC.cc` is not executable. This may be related to issue #53.

**Comment by j507** [comment]
It is not executable or it gets aborted? The last stand as far as I know is that it throws an assert due to the boundary conditions sanity checks we implemented. I have yet to see what you did in `fix_103` but does convergence rates are wrong.

**Comment by j507** [comment]
`GuermondNeumannBC.cc` is not running due to the asserts we implemented to ensure regularity of a general entity. 

In an hydrodynamic problem with Neumann boundary conditions solved through the monolithic approach, the pressure space is indirectly constrained through the Neumann boundary condition in the velocity space. When solving the same problem using projection methods, the regularity of the pressure space is ensured by the constrains set on the `phi` space. Even if leaving the pressure space fully unconstrained leads to a consistent formulation on paper, in our code leaving an entity fully unconstrained is not allowed.

**Comment by sebglane** [comment]
It is executable in the branch `fix_tolerance_values`, see PR #116.
